"""empty message

Revision ID: 064e67a2750c
Revises: 690aa8705d7e
Create Date: 2017-12-15 15:19:20.590587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '064e67a2750c'
down_revision = '690aa8705d7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'data_link')
    op.drop_column('links', 'metadata_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('metadata_link', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('links', sa.Column('data_link', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
