"""empty message

Revision ID: 078411637a40
Revises: 79c554cd0c94
Create Date: 2017-12-11 16:02:54.483734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '078411637a40'
down_revision = '79c554cd0c94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('links', 'order',
               existing_type=sa.SMALLINT(),
               nullable=False,
               existing_server_default=sa.text(u'1'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('links', 'order',
               existing_type=sa.SMALLINT(),
               nullable=True,
               existing_server_default=sa.text(u'1'))
    # ### end Alembic commands ###
