"""empty message

Revision ID: 0b909d4a4acd
Revises: 5ab4361c7066
Create Date: 2018-03-09 10:59:28.329612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b909d4a4acd'
down_revision = '5ab4361c7066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links_themes', sa.Column('layer', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links_themes', 'layer')
    # ### end Alembic commands ###
