"""empty message

Revision ID: 4f3b47ea9b46
Revises: cf9d872028a1
Create Date: 2020-11-09 10:00:08.773731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f3b47ea9b46'
down_revision = 'cf9d872028a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'reachable_last_check')
    op.drop_column('links', 'reachable')
    op.drop_column('sublinks', 'reachable_last_check')
    op.drop_column('sublinks', 'reachable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sublinks', sa.Column('reachable', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('sublinks', sa.Column('reachable_last_check', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('links', sa.Column('reachable', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('links', sa.Column('reachable_last_check', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
