"""empty message

Revision ID: 5254979ff775
Revises: 571750276cf5
Create Date: 2017-12-18 10:35:19.526303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5254979ff775'
down_revision = '571750276cf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('logo', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'logo')
    # ### end Alembic commands ###
