"""empty message

Revision ID: 571750276cf5
Revises: 064e67a2750c
Create Date: 2017-12-18 10:09:22.400031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571750276cf5'
down_revision = '064e67a2750c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'tags_title_key', 'tags', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'tags_title_key', 'tags', ['title'])
    # ### end Alembic commands ###
