"""empty message

Revision ID: 57cfab7eee25
Revises: 769cb2ec1aeb
Create Date: 2018-02-22 13:58:06.414065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57cfab7eee25'
down_revision = '769cb2ec1aeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links_themes', sa.Column('top', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links_themes', 'top')
    # ### end Alembic commands ###
