"""empty message

Revision ID: 690aa8705d7e
Revises: 078411637a40
Create Date: 2017-12-15 14:33:33.273263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '690aa8705d7e'
down_revision = '078411637a40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sublinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('reachable', sa.Boolean(), nullable=False),
    sa.Column('reachable_last_check', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('links_sublinks',
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('sublink_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.ForeignKeyConstraint(['sublink_id'], ['sublinks.id'], ),
    sa.PrimaryKeyConstraint('link_id', 'sublink_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('links_sublinks')
    op.drop_table('sublinks')
    op.drop_table('targets')
    # ### end Alembic commands ###
