"""empty message

Revision ID: 7104358a02c9
Revises: d638a831356f
Create Date: 2018-02-14 10:06:23.051040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7104358a02c9'
down_revision = 'd638a831356f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('links', 'search',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('links', 'search',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
