"""empty message

Revision ID: 725890358133
Revises: e3432e458169
Create Date: 2018-02-14 09:56:43.690272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '725890358133'
down_revision = 'e3432e458169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('search_title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'search_title')
    # ### end Alembic commands ###
