"""empty message

Revision ID: 769cb2ec1aeb
Revises: bff45b5e0f97
Create Date: 2018-02-21 14:40:47.234906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769cb2ec1aeb'
down_revision = 'bff45b5e0f97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('themes', sa.Column('descriptive_tags', sa.ARRAY(sa.String(length=255)), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('themes', 'descriptive_tags')
    # ### end Alembic commands ###
