"""empty message

Revision ID: 8fdf986cbe87
Revises: 7104358a02c9
Create Date: 2018-02-16 11:31:27.617045

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8fdf986cbe87'
down_revision = '7104358a02c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('authorship_organisation', sa.ARRAY(sa.String(length=255)), nullable=True))
    op.drop_column('links', 'authorship_place')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('authorship_place', postgresql.ARRAY(sa.VARCHAR(length=255)), autoincrement=False, nullable=True))
    op.drop_column('links', 'authorship_organisation')
    # ### end Alembic commands ###
