"""empty message

Revision ID: 9c35572fea40
Revises: 0b909d4a4acd
Create Date: 2018-03-09 11:00:42.235325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c35572fea40'
down_revision = '0b909d4a4acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links_themes', 'feature_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links_themes', sa.Column('feature_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
