"""empty message

Revision ID: a5c49130bdce
Revises: 5254979ff775
Create Date: 2017-12-18 14:12:27.245201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5c49130bdce'
down_revision = '5254979ff775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('parent_order', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'parent_order')
    # ### end Alembic commands ###
