"""empty message

Revision ID: b625bd3eb7fd
Revises: 57cfab7eee25
Create Date: 2018-02-22 15:02:50.247815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b625bd3eb7fd'
down_revision = '57cfab7eee25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links_themes', sa.Column('type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links_themes', 'type')
    # ### end Alembic commands ###
