"""empty message

Revision ID: c8fd87091f51
Revises: 309875d3ad25
Create Date: 2020-10-22 16:02:15.142027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8fd87091f51'
down_revision = '309875d3ad25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('annex', sa.SmallInteger(), nullable=False),
    sa.Column('short', sa.String(length=2), nullable=False),
    sa.Column('theme_de', sa.String(length=255), nullable=False),
    sa.Column('theme_en', sa.String(length=255), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspire_annex'), 'inspire', ['annex'], unique=False)
    op.create_index(op.f('ix_inspire_language'), 'inspire', ['language'], unique=False)
    op.create_table('links_inspire',
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('inspire_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inspire_id'], ['inspire.id'], ),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.PrimaryKeyConstraint('link_id', 'inspire_id')
    )
    op.drop_table('temp_inspire')
    op.drop_table('temp_links_inspire')
    op.drop_column('links', 'inspire_annex_theme')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('inspire_annex_theme', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_table('temp_links_inspire',
    sa.Column('inspire_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('link_id', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('temp_inspire',
    sa.Column('ogc_fid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('annex', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('short', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('theme', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ogc_fid', name='temp_inspire_pkey')
    )
    op.drop_table('links_inspire')
    op.drop_index(op.f('ix_inspire_language'), table_name='inspire')
    op.drop_index(op.f('ix_inspire_annex'), table_name='inspire')
    op.drop_table('inspire')
    # ### end Alembic commands ###
