"""empty message

Revision ID: c973318d8479
Revises: ba5c83f5c487
Create Date: 2017-12-04 14:01:07.168978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c973318d8479'
down_revision = 'ba5c83f5c487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('public', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'public')
    # ### end Alembic commands ###
