"""empty message

Revision ID: cf9d872028a1
Revises: b8dbfccc5afb
Create Date: 2020-10-26 09:01:38.139730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf9d872028a1'
down_revision = 'b8dbfccc5afb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_inspire_id'), 'inspire', ['id'], unique=False)
    op.create_index(op.f('ix_links_id'), 'links', ['id'], unique=False)
    op.create_index(op.f('ix_links_link'), 'links', ['link'], unique=False)
    op.create_index(op.f('ix_links_title'), 'links', ['title'], unique=False)
    op.create_index(op.f('ix_links_inspire_inspire_id'), 'links_inspire', ['inspire_id'], unique=False)
    op.create_index(op.f('ix_links_inspire_link_id'), 'links_inspire', ['link_id'], unique=False)
    op.create_index(op.f('ix_links_sublinks_link_id'), 'links_sublinks', ['link_id'], unique=False)
    op.create_index(op.f('ix_links_sublinks_sublink_id'), 'links_sublinks', ['sublink_id'], unique=False)
    op.create_index(op.f('ix_links_tags_link_id'), 'links_tags', ['link_id'], unique=False)
    op.create_index(op.f('ix_links_tags_tag_id'), 'links_tags', ['tag_id'], unique=False)
    op.create_index(op.f('ix_links_themes_link_id'), 'links_themes', ['link_id'], unique=False)
    op.create_index(op.f('ix_links_themes_theme_id'), 'links_themes', ['theme_id'], unique=False)
    op.create_index(op.f('ix_sublinks_id'), 'sublinks', ['id'], unique=False)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_themes_id'), 'themes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_themes_id'), table_name='themes')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index(op.f('ix_sublinks_id'), table_name='sublinks')
    op.drop_index(op.f('ix_links_themes_theme_id'), table_name='links_themes')
    op.drop_index(op.f('ix_links_themes_link_id'), table_name='links_themes')
    op.drop_index(op.f('ix_links_tags_tag_id'), table_name='links_tags')
    op.drop_index(op.f('ix_links_tags_link_id'), table_name='links_tags')
    op.drop_index(op.f('ix_links_sublinks_sublink_id'), table_name='links_sublinks')
    op.drop_index(op.f('ix_links_sublinks_link_id'), table_name='links_sublinks')
    op.drop_index(op.f('ix_links_inspire_link_id'), table_name='links_inspire')
    op.drop_index(op.f('ix_links_inspire_inspire_id'), table_name='links_inspire')
    op.drop_index(op.f('ix_links_title'), table_name='links')
    op.drop_index(op.f('ix_links_link'), table_name='links')
    op.drop_index(op.f('ix_links_id'), table_name='links')
    op.drop_index(op.f('ix_inspire_id'), table_name='inspire')
    # ### end Alembic commands ###
