"""empty message

Revision ID: d638a831356f
Revises: 725890358133
Create Date: 2018-02-14 10:01:21.694330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd638a831356f'
down_revision = '725890358133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('search', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'search')
    # ### end Alembic commands ###
